#!/usr/bin/env python3
"""Generate a per-program symbol-id -> name table from every .asm
file's LOADSYM comments (`LOADSYM Rn, <id>  ; 'name ...`).

Symbol ids are NOT globally interned across .asm files -- each
bootstrap demo assigns its own small numeric ids independently, and the
same id can mean a real symbol in one program (e.g. 900 = 'third in
bootstrap_third_demo.asm) and a throwaway NIL-derivation helper in
another (the "LOADSYM 900; LOADSYM 901; EQ -> NIL" trick most bootstrap
demos use). A single global id->name table would silently show the
wrong name depending on which program actually happens to be loaded on
the board. So the table is keyed per source file (by basename, matching
the .bin monitor.py uploads), not merged into one flat dict.

Closes FPGA-SYMBOL-TABLE-HOST-TOOL: no PC-side interned-symbol-name
printer existed before this -- monitor.py's REG/HEAP output showed raw
numeric ids (e.g. VAL:930) with no way to know that means 'a without
manually grepping the .asm comments of whichever program is running.

Usage: python3 gen_symbol_table.py > symbol_table.py
"""
import glob
import re
import sys

LOADSYM_RE = re.compile(r"LOADSYM\s+R\d+,\s*(\d+)\s*;\s*'([A-Za-z0-9_?!-]+)")

# Special forms defined via .define in constants.inc, not an inline
# LOADSYM literal -- no per-file comment to scrape, but every .asm that
# .includes constants.inc shares these two ids identically, so they're
# added to every program's table.
SPECIAL_FORMS = {50: "quote", 80: "cond"}


def scan_file(path):
    table = dict(SPECIAL_FORMS)
    conflicts = {}
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            m = LOADSYM_RE.search(line)
            if not m:
                continue
            sym_id, name = int(m.group(1)), m.group(2)
            if sym_id in table and table[sym_id] != name:
                conflicts.setdefault(sym_id, {table[sym_id], name}).add(name)
            table[sym_id] = name
    return table, conflicts


def main():
    programs = {}
    for path in sorted(glob.glob("*.asm")):
        basename = path[:-4]  # strip .asm, matches the .bin monitor.py uploads
        table, conflicts = scan_file(path)
        if conflicts:
            for sym_id, names in sorted(conflicts.items()):
                print(f"# WARNING: {path}: id {sym_id} reused for multiple names within the same program: {sorted(names)} -- last LOADSYM wins", file=sys.stderr)
        programs[basename] = table

    print("# Auto-generated by gen_symbol_table.py -- do not edit by hand.")
    print("# Regenerate after adding/changing LOADSYM literals in any .asm file.")
    print("#")
    print("# Keyed per source file, NOT a single global id->name table --")
    print("# symbol ids are not interned across separate bootstrap demos, see")
    print("# this script's own header comment before merging these dicts.")
    print("PROGRAM_SYMBOLS = {")
    for basename in sorted(programs):
        print(f"    {basename!r}: {{")
        for sym_id in sorted(programs[basename]):
            print(f"        {sym_id}: {programs[basename][sym_id]!r},")
        print("    },")
    print("}")


if __name__ == "__main__":
    main()
