#!/usr/bin/env python3
"""Generate a per-program symbol-id -> name table from every .asm
file's LOADSYM comments (`LOADSYM Rn, <id>  ; 'name ...`).

Symbol ids are NOT globally interned across .asm files -- each
bootstrap demo assigns its own small numeric ids independently, and the
same id can mean a real symbol in one program (e.g. 900 = 'third in
bootstrap_third_demo.asm) and a throwaway NIL-derivation helper in
another (the "LOADSYM 900; LOADSYM 901; EQ -> NIL" trick most bootstrap
demos use). A single global id->name table would silently show the
wrong name depending on which program actually happens to be loaded on
the board. So the table is keyed per source file (by basename, matching
the .bin monitor.py uploads), not merged into one flat dict.

Closes FPGA-SYMBOL-TABLE-HOST-TOOL: no PC-side interned-symbol-name
printer existed before this -- monitor.py's REG/HEAP output showed raw
numeric ids (e.g. VAL:930) with no way to know that means 'a without
manually grepping the .asm comments of whichever program is running.

Usage: python3 gen_symbol_table.py > symbol_table.py
"""
import glob
import os
import re
import sys

LOADSYM_RE = re.compile(r"LOADSYM\s+R\d+,\s*(\d+)\s*;\s*'([A-Za-z0-9_?!-]+)")

# Special forms defined via .define in constants.inc, not an inline
# LOADSYM literal -- no per-file comment to scrape, but every .asm that
# .includes constants.inc shares these two ids identically, so they're
# added to every program's table.
#
# The *spelling* printed for each ("quote", "cond") is not this script's
# to invent: it must come from my-lisp's semantic-registry.wsm, the one
# canonical source of surface spellings (see
# docs/canon-symbol-registry-fpga-lisp-part.md). Hardcoding the English
# word here would silently drift the moment the registry's own English
# surface for semantic id 0001/0007 changes -- the same class of bug
# already found in my-lisp's LSP, wsm-my-lisp's eval.rs, and cml's
# lower.rs/semantic.rs. fpga-lisp's hardware symbol ids (50, 80, from
# fpga/asm/constants.inc) are a separate, fixed numbering space and are
# NOT looked up in the registry -- only the printed name is.

# fpga hardware symbol id -> semantic-registry.wsm numeric id.
SPECIAL_FORM_REGISTRY_IDS = {50: "0001", 80: "0007"}

REGISTRY_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..", "my-lisp", "lib", "surface", "semantic-registry.wsm",
)

# Minimal single-line scraper for exactly the "(<id> (en <word> ...) ...)"
# shape -- not a general s-expression reader, deliberately scoped to the
# two ids this script needs (see SPECIAL_FORM_REGISTRY_IDS).
REGISTRY_EN_RE = re.compile(r"^\s*\((\d{4})\s+\(en\s+(\S+)\s")


def load_special_forms(registry_path=REGISTRY_PATH):
    """Fail-closed: raise rather than silently falling back to a guess
    if the registry is missing or doesn't define an English surface for
    a semantic id this script needs."""
    wanted = set(SPECIAL_FORM_REGISTRY_IDS.values())
    found = {}
    with open(registry_path, "r", encoding="utf-8") as f:
        for line in f:
            m = REGISTRY_EN_RE.match(line)
            if m and m.group(1) in wanted:
                found[m.group(1)] = m.group(2)
    missing = wanted - found.keys()
    if missing:
        raise ValueError(
            f"semantic-registry.wsm at {registry_path!r} is missing an "
            f"'en' surface for semantic id(s) {sorted(missing)}"
        )
    return {
        hw_id: found[registry_id]
        for hw_id, registry_id in SPECIAL_FORM_REGISTRY_IDS.items()
    }


SPECIAL_FORMS = load_special_forms()


def scan_file(path):
    table = dict(SPECIAL_FORMS)
    conflicts = {}
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            m = LOADSYM_RE.search(line)
            if not m:
                continue
            sym_id, name = int(m.group(1)), m.group(2)
            if sym_id in table and table[sym_id] != name:
                conflicts.setdefault(sym_id, {table[sym_id], name}).add(name)
            table[sym_id] = name
    return table, conflicts


def main():
    programs = {}
    for path in sorted(glob.glob("*.asm")):
        basename = path[:-4]  # strip .asm, matches the .bin monitor.py uploads
        table, conflicts = scan_file(path)
        if conflicts:
            for sym_id, names in sorted(conflicts.items()):
                print(f"# WARNING: {path}: id {sym_id} reused for multiple names within the same program: {sorted(names)} -- last LOADSYM wins", file=sys.stderr)
        programs[basename] = table

    print("# Auto-generated by gen_symbol_table.py -- do not edit by hand.")
    print("# Regenerate after adding/changing LOADSYM literals in any .asm file.")
    print("#")
    print("# Keyed per source file, NOT a single global id->name table --")
    print("# symbol ids are not interned across separate bootstrap demos, see")
    print("# this script's own header comment before merging these dicts.")
    print("PROGRAM_SYMBOLS = {")
    for basename in sorted(programs):
        print(f"    {basename!r}: {{")
        for sym_id in sorted(programs[basename]):
            print(f"        {sym_id}: {programs[basename][sym_id]!r},")
        print("    },")
    print("}")


if __name__ == "__main__":
    main()
