; fpga/canon/gen-sid8-hardware-admission.lisp
;
; #19 FPGA-SID8-1 — mechanical hardware projection only.
;
; Input authority:
;   fpga/canon/execution-spec.lisp
;
; The execution spec has already been checked against pinned upstream my-lisp
; Canon by gen-primitive-table.lisp. This generator does not define language
; meaning. It only materializes the already-reviewed relation:
;
;   exact Canon Sid8 -> FPGA-local PRIM_* mechanism id
;
; Output is SystemVerilog with an explicit logic [7:0] SID port. Local
; primitive ids are mechanism data and deliberately use their own width.
;
; Usage:
;   my-lisp fpga/canon/gen-sid8-hardware-admission.lisp OUTPUT.sv

(def second (lambda (x) (car (cdr x))))
(def third (lambda (x) (car (cdr (cdr x)))))
(def fourth (lambda (x) (car (cdr (cdr (cdr x))))))

(def fail-closed
  (lambda (msg)
    (eval (string->symbol (string-append "FPGA-SID8-HW-FAIL-CLOSED: " msg)))))

(def entry-line
  (lambda (entry)
    (string-append
      "      8'b"
      (string-append
        (write-to-string (car entry))
        (string-append
          ": primitive_id = 16'd"
          (string-append
            (write-to-string (fourth entry))
            (string-append
              "; // "
              (string-append (write-to-string (third entry)) "\n"))))))))

(def entry-lines
  (lambda (entries)
    (cond
      ((atom entries) (structural-kind empty-list) "")
      ((atom entries) (structural-kind pair)
       (string-append (entry-line (car entries)) (entry-lines (cdr entries)))))))

(def spec-forms (read-all (read-file "fpga/canon/execution-spec.lisp")))

(cond
  ((equal? (car spec-forms) (quote (binary 8))) (structural-relation same)
   (quote ()))
  ((equal? (car spec-forms) (quote (binary 8))) (structural-relation distinct)
   (fail-closed "execution spec must declare (binary 8)")))

(def spec-form (second spec-forms))

(cond
  ((eq (car spec-form) (quote fpga-primitive-execution-spec)) (identity-relation same)
   (quote ()))
  ((eq (car spec-form) (quote fpga-primitive-execution-spec)) (identity-relation distinct)
   (fail-closed "unexpected execution spec root")))

(def entries (cdr spec-form))

(def generated
  (string-append
    "// Generated by fpga/canon/gen-sid8-hardware-admission.lisp -- DO NOT EDIT.\n"
    (string-append
      "// Input: fpga/canon/execution-spec.lisp\n"
      (string-append
        "// Canon SID is exactly 8 bits. primitive_id is FPGA-local mechanism data.\n"
        (string-append
          "module fpga_sid8_admission (\n"
          (string-append
            "    input  logic [7:0]  sid,\n"
            (string-append
              "    output logic        admitted,\n"
              (string-append
                "    output logic [15:0] primitive_id\n"
                (string-append
                  ");\n"
                  (string-append
                    "  always_comb begin\n"
                    (string-append
                      "    admitted = 1'b1;\n"
                      (string-append
                        "    primitive_id = 16'd0;\n"
                        (string-append
                          "    case (sid)\n"
                          (string-append
                            (entry-lines entries)
                            (string-append
                              "      default: begin\n"
                              (string-append
                                "        admitted = 1'b0;\n"
                                (string-append
                                  "        primitive_id = 16'd0;\n"
                                  (string-append
                                    "      end\n"
                                    (string-append
                                      "    endcase\n"
                                      (string-append
                                        "  end\n"
                                        "endmodule\n"))))))))))))))))))))

(cond
  ((atom *argv*) (structural-kind empty-list)
   (fail-closed "output path argument required"))
  ((atom *argv*) (structural-kind pair)
   (write-file (car *argv*) generated)))
