; fpga/canon/gen-sid8-hardware-admission.lisp
;
; #19 FPGA-SID8-1 — mechanical hardware projection only.
;
; Input authority:
;   fpga/canon/execution-spec.lisp
;
; The execution spec has already been checked against pinned upstream my-lisp
; Canon by gen-primitive-table.lisp. This generator does not define language
; meaning. It only materializes the already-reviewed relation:
;
;   exact Canon Sid8 -> FPGA-local PRIM_* mechanism id
;
; Output is SystemVerilog with an explicit logic [7:0] SID port. Local
; primitive ids are mechanism data and deliberately use their own width.

(def second (lambda (x) (car (cdr x))))
(def third (lambda (x) (car (cdr (cdr x)))))
(def fourth (lambda (x) (car (cdr (cdr (cdr x))))))
(def fifth (lambda (x) (car (cdr (cdr (cdr (cdr x)))))))

(def fail-closed
  (lambda (msg)
    (eval (string->symbol (string-append "FPGA-SID8-HW-FAIL-CLOSED: " msg)))))

(def emit-entry
  (lambda (entry)
    ((lambda ()
       (def canon-sid (car entry))
       (def primitive-const (third entry))
       (def local-id (fourth entry))
       (princ "      8'b")
       (princ (write-to-string canon-sid))
       (princ ": primitive_id = 16'd")
       (princ (write-to-string local-id))
       (princ "; // ")
       (princ (write-to-string primitive-const))
       (princ "\n")))))

(def emit-entries
  (lambda (entries)
    (cond
      ((atom entries) (structural-kind empty-list) (quote ()))
      ((atom entries) (structural-kind pair)
       ((lambda ()
          (emit-entry (car entries))
          (emit-entries (cdr entries))))))))

(def spec-forms (read-all (read-file "fpga/canon/execution-spec.lisp")))

(cond
  ((equal? (car spec-forms) (quote (binary 8))) (structural-relation same)
   (quote ()))
  ((equal? (car spec-forms) (quote (binary 8))) (structural-relation distinct)
   (fail-closed "execution spec must declare (binary 8)")))

(def spec-form (second spec-forms))

(cond
  ((eq (car spec-form) (quote fpga-primitive-execution-spec)) (identity-relation same)
   (quote ()))
  ((eq (car spec-form) (quote fpga-primitive-execution-spec)) (identity-relation distinct)
   (fail-closed "unexpected execution spec root")))

(def entries (cdr spec-form))

(princ "// Generated by fpga/canon/gen-sid8-hardware-admission.lisp -- DO NOT EDIT.\n")
(princ "// Input: fpga/canon/execution-spec.lisp\n")
(princ "// Canon SID is exactly 8 bits. primitive_id is FPGA-local mechanism data.\n")
(princ "module fpga_sid8_admission (\n")
(princ "    input  logic [7:0]  sid,\n")
(princ "    output logic        admitted,\n")
(princ "    output logic [15:0] primitive_id\n")
(princ ");\n")
(princ "  always_comb begin\n")
(princ "    admitted = 1'b1;\n")
(princ "    primitive_id = 16'd0;\n")
(princ "    case (sid)\n")
(emit-entries entries)
(princ "      default: begin\n")
(princ "        admitted = 1'b0;\n")
(princ "        primitive_id = 16'd0;\n")
(princ "      end\n")
(princ "    endcase\n")
(princ "  end\n")
(princ "endmodule\n")

(quote ())
