; Generated by juv4uk/sens/.github/workflows/sync-language-contract.yml
; This pins the observed upstream authority. It does NOT claim that the
; consumer implements the pinned contract version.
(contract-lock
  (source
    (repository juv4uk/sens)
    (branch main)
    (path language-contract.lisp))
  (revision "0a791bece07b5693ef6ec4e90dd92e4bac689e7f")
  (sha256 "5781d881c372aeb4df2b29bf01961ce734628224185e20151b0537175c9b4108"))
