; Generated by juv4uk/sens/.github/workflows/sync-language-contract.yml
; This pins the observed upstream authority. It does NOT claim that the
; consumer implements the pinned contract version.
(contract-lock
  (source
    (repository juv4uk/sens)
    (branch main)
    (path language-contract.lisp))
  (revision "e345aa3f0c3db8d915468f6d5eddd39dbaf4a708")
  (sha256 "9768f683e90cfb56ca95675d1f6ac0e6ede91e21cebe97e20b455cf1b3094791"))
